### ISSUE TITLE
getting an error when starting Loader.main func

### ISSUE THREAD

**Issue by CrazyFish159** [MrExplode/ShowManager#86]
getting an error when starting Loader.main func

```
2022-10-21 15:33:58,322 main WARN Advanced terminal features are not available in this environment
[15:33:58] [main/INFO]: Loading ShowManager...
[15:33:58] [main/INFO]: Looking for possible outputs...
[15:33:58] [main/INFO]: Loading EventBus...
[15:33:58] [main/INFO]: Loading projects...
[15:33:58] [main/INFO]: Couldn't find last project descriptor
[15:33:58] [main/INFO]: Starting OSCHandler...
[15:33:58] [main/INFO]: Loading HttpHandler...
[15:33:58] [main/INFO]: Logging initialized @1027ms to org.eclipse.jetty.util.log.Slf4jLog
[15:33:58] [main/ERROR]: java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:279) ~[?:?]
	at io.javalin.jetty.ConfigurableHandler.getResourceBase(JettyResourceHandler.kt:98) ~[javalin-4.6.4.jar:4.6.4]
	at io.javalin.jetty.ConfigurableHandler.<init>(JettyResourceHandler.kt:70) ~[javalin-4.6.4.jar:4.6.4]
	at io.javalin.jetty.JettyResourceHandler.addStaticFileConfig(JettyResourceHandler.kt:33) ~[javalin-4.6.4.jar:4.6.4]
	at io.javalin.core.JavalinConfig.addStaticFiles(JavalinConfig.java:134) ~[javalin-4.6.4.jar:4.6.4]
	at me.sunstorm.showmanager.http.HttpHandler.lambda$new$2(HttpHandler.java:61) ~[main/:?]
	at io.javalin.core.JavalinConfig.applyUserConfig(JavalinConfig.java:205) ~[javalin-4.6.4.jar:4.6.4]
	at io.javalin.Javalin.create(Javalin.java:93) ~[javalin-4.6.4.jar:4.6.4]
	at me.sunstorm.showmanager.http.HttpHandler.<init>(HttpHandler.java:44) ~[main/:?]
	at me.sunstorm.showmanager.ShowManager.<init>(ShowManager.java:80) ~[main/:?]
	at me.sunstorm.showmanager.Loader.main(Loader.java:11) ~[main/:?]
 Fatal error
```

any idea how to fix it?

**Comment by MrExplode** [comment]
You have to add the frontend location to either a java property named `showmanager.dist` in the command line or an environment value with the same name. See: [install details](https://github.com/MrExplode/ShowManager#showmanager-frontend)

**Comment by MrExplode** [comment]
I assume the issue has been resolved.
